name: Landing Page Automation

on:
  push:
    branches:
      - main  # Kamu bisa menambahkan branch lain sesuai kebutuhan
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest  # Kamu bisa mengganti dengan OS lain sesuai kebutuhan

    steps:
      # Step 1:  Checkout kode repositori
      - name: Checkout repository
        uses: actions/checkout@v2

      # Step 2: Set up Python environment
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      # Step 3: Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # Step 4: Install WebDriver Manager
      - name: Install WebDriver Manager
        run: |
          pip install webdriver-manager

      # Step : Run Robot Framework tests
      - name: Run Robot Framework tests
        run: |
          robot tests/01_LandingPage.robot

      # Step : Upload test results as artifacts
      - name: Upload Robot Framework reports
        uses: actions/upload-artifact@v3
        with:
          name: robot-reports
          path: reports/
